import { CLEAR, hex, Raster, type Rgba } from './raster.ts';

// Placeholder art for the default pack, drawn in code so it can be regenerated byte-for-byte (spec §9.5).
// Real art replaces it at M10.

const F = 16; // character frame and tile size

const HERO = [
  '................',
  '......oooo......',
  '.....ohhhho.....',
  '....ohhhhhho....',
  '....ohhsssso....',
  '....ohsesseo....',
  '....ohhsssso.w..',
  '.....obbbbo..w..',
  '....obbllbbo.w..',
  '...osbbbbbbsow..',
  '....obbbbbbo.w..',
  '....oppppppo....',
  '....opp..ppo....',
  '....opp..ppo....',
  '....off..ffo....',
  '....ooo..ooo....',
];

const COUNCILLOR = [
  '.......oo.......',
  '......ohho......',
  '.....ohhhho.....',
  '....ohhhhhho....',
  '...oooooooooo...',
  '....osssssso....',
  '....osesssso....',
  '....owwwwwwo....',
  '...orrwwwwrro...',
  '..orrrwwwwrrro..',
  '..orrrrwwrrrro..',
  '..orrrrrrrrrro..',
  '..orrryyyyrrro..',
  '..orrrrrrrrrro..',
  '..orrrrrrrrrro..',
  '..oooooooooooo..',
];

const INK = hex('#1a1420');
const SKIN = hex('#f1c19a');
const EYE = hex('#1b1b1b');

type Palette = Record<string, Rgba>;

export interface CharacterArt {
  key: string;
  role: 'hero' | 'councillor';
  palette: Palette;
  backdrop: Rgba;
}

export const CHARACTERS: CharacterArt[] = [
  {
    key: 'hero.paladin',
    role: 'hero',
    backdrop: hex('#2d4a7a'),
    palette: {
      o: INK,
      h: hex('#c8ccd4'),
      s: SKIN,
      e: EYE,
      b: hex('#3a6ac0'),
      l: hex('#f2c230'),
      w: hex('#e8e8f0'),
      p: hex('#8a90a0'),
      f: hex('#4a4a58'),
    },
  },
  {
    key: 'hero.barbarian',
    role: 'hero',
    backdrop: hex('#6a2a20'),
    palette: {
      o: INK,
      h: hex('#c0392b'),
      s: hex('#e8b088'),
      e: EYE,
      b: hex('#8a5a3a'),
      l: hex('#3a2a1a'),
      w: hex('#b8c0c8'),
      p: hex('#5a4030'),
      f: hex('#2a1d14'),
    },
  },
  {
    key: 'hero.ranger',
    role: 'hero',
    backdrop: hex('#2a5a2a'),
    palette: {
      o: INK,
      h: hex('#3f8a3a'),
      s: SKIN,
      e: EYE,
      b: hex('#7a9a3a'),
      l: hex('#6b4423'),
      w: hex('#9a6a3b'),
      p: hex('#4a3a2a'),
      f: hex('#2a1d14'),
    },
  },
  {
    key: 'hero.rogue',
    role: 'hero',
    backdrop: hex('#3a2a4a'),
    palette: {
      o: INK,
      h: hex('#4a3a5a'),
      s: hex('#d9a77f'),
      e: EYE,
      b: hex('#5a5a6a'),
      l: hex('#8a2a4a'),
      w: hex('#c8c8d0'),
      p: hex('#2a2a3a'),
      f: hex('#1a1a24'),
    },
  },
  {
    key: 'councillor.elder',
    role: 'councillor',
    backdrop: hex('#4a3a6a'),
    palette: {
      o: INK,
      h: hex('#5a3d8a'),
      s: SKIN,
      e: EYE,
      w: hex('#e8e8e8'),
      r: hex('#6e4aa8'),
      y: hex('#f2c230'),
    },
  },
  {
    key: 'councillor.default',
    role: 'councillor',
    backdrop: hex('#2a5a5a'),
    palette: {
      o: INK,
      h: hex('#2d6a6a'),
      s: hex('#d9a77f'),
      e: EYE,
      w: hex('#c8c8c8'),
      r: hex('#3a8a8a'),
      y: hex('#e86a3a'),
    },
  },
];

export const ANIMATIONS = ['idle', 'walk', 'work'] as const;
export const FRAMES = 4;

/** One animation frame as template rows: bobbing, stepping or tool motion applied to the base pose. */
function frameRows(
  base: readonly string[],
  role: CharacterArt['role'],
  animation: (typeof ANIMATIONS)[number],
  i: number,
): string[] {
  let rows = base.map((r) => r);
  const shiftDown = (n: number) => {
    rows = [...Array(n).fill('.'.repeat(F)), ...rows.slice(0, F - n)];
  };
  const liftColumns = (from: number, to: number, top: number) => {
    // Move pixels in columns [from, to) of rows top..15 up by one.
    const grid = rows.map((r) => [...r]);
    for (let y = top; y < F; y++) {
      for (let x = from; x < to; x++) {
        (grid[y - 1] as string[])[x] = (grid[y] as string[])[x] as string;
        (grid[y] as string[])[x] = '.';
      }
    }
    rows = grid.map((g) => g.join(''));
  };
  const moveKey = (key: string, dy: number) => {
    if (dy === 0) return;
    const grid = rows.map((r) => [...r]);
    const cells: [number, number][] = [];
    grid.forEach((row, y) => {
      row.forEach((ch, x) => {
        if (ch === key) cells.push([x, y]);
      });
    });
    for (const [x, y] of cells) (grid[y] as string[])[x] = '.';
    for (const [x, y] of cells) if (y + dy >= 0 && y + dy < F) (grid[y + dy] as string[])[x] = key;
    rows = grid.map((g) => g.join(''));
  };

  if (animation === 'idle') {
    if (i >= 2) shiftDown(1);
  } else if (animation === 'walk') {
    if (role === 'hero') {
      if (i === 1) liftColumns(4, 8, 12);
      if (i === 3) liftColumns(8, 12, 12);
    } else if (i % 2 === 1) {
      liftColumns(i === 1 ? 2 : 8, i === 1 ? 8 : 14, 14);
    }
    if (i % 2 === 1) shiftDown(1);
  } else if (role === 'hero') {
    moveKey('w', [-1, 0, 1, 0][i] ?? 0);
  } else {
    // councillor at work: a spark of insight travels up beside them
    const grid = rows.map((r) => [...r]);
    (grid[9 - i] as string[])[14] = 'y';
    rows = grid.map((g) => g.join(''));
  }
  return rows;
}

export function characterSheet(art: CharacterArt): Raster {
  const base = art.role === 'hero' ? HERO : COUNCILLOR;
  const sheet = new Raster(F * FRAMES, F * ANIMATIONS.length);
  ANIMATIONS.forEach((animation, row) => {
    for (let i = 0; i < FRAMES; i++) {
      sheet.pattern(i * F, row * F, frameRows(base, art.role, animation, i), art.palette);
    }
  });
  return sheet;
}

export function portrait(art: CharacterArt): Raster {
  const p = new Raster(64, 64);
  p.rect(0, 0, 64, 64, INK);
  p.rect(2, 2, 60, 60, art.backdrop);
  const sprite = new Raster(F, F);
  sprite.pattern(0, 0, art.role === 'hero' ? HERO : COUNCILLOR, art.palette);
  p.blit(sprite, 8, 10, 3);
  return p;
}

// ---------- map ----------

const WATER = hex('#2b5f9e');
const WATER_LIGHT = hex('#336db0');
const WAVE = hex('#8fc1ef');
const GRASS = hex('#5dab3c');
const GRASS_DARK = hex('#4a9530');
const SAND = hex('#e8d48a');
const SAND_DARK = hex('#cdb56a');
const CLIFF = hex('#8a5a2e');
const CLIFF_DARK = hex('#5e3b1c');
const FOAM = hex('#d8ecff');
const DOT = hex('#f3ead2');
const DOT_SHADOW = hex('#1f4a7c');

/** Tile strip: water ×4 (animated), grass, sand, shore, path dot. */
export const TILE_INDEX = { water: 0, grass: 4, sand: 5, shore: 6, pathDot: 7 } as const;

export function tiles(): Raster {
  const t = new Raster(F * 8, F);
  for (let f = 0; f < 4; f++) {
    const x0 = f * F;
    t.rect(x0, 0, F, F, WATER);
    t.rect(x0, 8, F, 8, WATER_LIGHT);
    t.rect(x0 + ((2 + f * 3) % F), 4, 3, 1, WAVE);
    t.rect(x0 + ((9 + f * 3) % 13), 11, 3, 1, WAVE);
  }
  t.rect(4 * F, 0, F, F, GRASS);
  for (const [x, y] of [
    [3, 4],
    [10, 2],
    [7, 11],
    [13, 9],
  ] as const)
    t.rect(4 * F + x, y, 1, 2, GRASS_DARK);
  t.rect(5 * F, 0, F, F, SAND);
  for (const [x, y] of [
    [2, 3],
    [11, 6],
    [6, 12],
  ] as const)
    t.set(5 * F + x, y, SAND_DARK);
  t.rect(6 * F, 0, F, 10, GRASS);
  t.rect(6 * F, 10, F, 6, SAND);
  t.rect(6 * F, 10, F, 1, SAND_DARK);
  t.rect(7 * F + 7, 7, 2, 2, DOT_SHADOW);
  t.rect(7 * F + 7, 6, 2, 2, DOT);
  return t;
}

/** One island at minimum width: left cap 48, one repeatable middle 32, right cap 48; 96 tall (§9.2). */
export function island(): Raster {
  const w = 128;
  const img = new Raster(w, 96);
  const insetTop = [8, 5, 3, 2, 1, 1];
  for (let r = 0; r < 96; r++) {
    const inset = r >= 84 ? 2 + (r - 84) : r < 6 ? (insetTop[r] as number) : 0;
    const color = r < 2 ? SAND : r < 58 ? GRASS : r < 64 ? SAND : r < 86 ? CLIFF : FOAM;
    img.rect(inset, r, w - inset * 2, 1, color);
    if (color === GRASS) {
      img.rect(inset, r, 2, 1, SAND);
      img.rect(w - inset - 2, r, 2, 1, SAND);
    }
    if (color === CLIFF) {
      for (let x = inset + 3; x < w - inset; x += 8)
        img.set(x + (r % 3 === 0 ? 1 : 0), r, CLIFF_DARK);
    }
    if (r === 63) img.rect(inset, r, w - inset * 2, 1, SAND_DARK);
  }
  // Tufts repeat every 32 px so the middle slice tiles seamlessly.
  for (let x = 6; x < w - 6; x += 32) {
    for (const [dx, dy] of [
      [4, 10],
      [15, 30],
      [24, 18],
      [9, 44],
    ] as const) {
      if (x + dx + 2 > w - 4) continue; // keep the sand rim clear
      img.rect(x + dx, dy, 1, 2, GRASS_DARK);
      img.set(x + dx + 1, dy + 1, GRASS_DARK);
    }
  }
  return img;
}

export const TASK_POINT_COLORS = {
  locked: hex('#8a8a8a'),
  active: hex('#f2c230'),
  done: hex('#4fd16a'),
  underReview: hex('#6aa8ff'),
} as const;

/** Task point states left to right, each with its own icon so colour is never the only signal (§7.4). */
export function taskPoints(states: readonly (keyof typeof TASK_POINT_COLORS)[]): Raster {
  const img = new Raster(F * states.length, F);
  states.forEach((state, i) => {
    const x = i * F;
    const color = TASK_POINT_COLORS[state];
    img.rect(x + 2, 3, 12, 11, INK);
    img.rect(x + 3, 2, 10, 13, INK);
    img.rect(x + 3, 3, 10, 10, color);
    img.rect(x + 4, 2, 8, 12, color);
    if (state === 'locked') {
      img.rect(x + 6, 5, 4, 1, INK);
      img.rect(x + 5, 6, 1, 2, INK);
      img.rect(x + 10, 6, 1, 2, INK);
      img.rect(x + 5, 8, 6, 4, INK);
    } else if (state === 'active') {
      img.rect(x + 7, 5, 2, 4, INK);
      img.rect(x + 7, 10, 2, 2, INK);
    } else if (state === 'done') {
      for (const [dx, dy] of [
        [5, 8],
        [6, 9],
        [7, 10],
        [8, 9],
        [9, 8],
        [10, 7],
        [11, 6],
      ] as const)
        img.set(x + dx, dy, INK);
    } else {
      img.rect(x + 5, 7, 6, 3, INK);
      img.rect(x + 7, 8, 2, 1, color);
    }
  });
  return img;
}

export function hut(): Raster {
  const img = new Raster(64, 64);
  img.rect(8, 28, 48, 34, hex('#7a4a24'));
  for (let i = 0; i < 34; i += 4) img.rect(8, 28 + i, 48, 1, hex('#5e3818'));
  for (let r = 0; r < 28; r++) {
    const half = 4 + r;
    img.rect(32 - half, r + 2, half * 2, 1, r % 4 === 0 && r > 0 ? hex('#8a2a20') : hex('#b8392b'));
  }
  img.rect(26, 44, 12, 18, hex('#2a1a10'));
  img.rect(35, 53, 1, 2, hex('#f2c230'));
  img.rect(12, 36, 8, 7, SAND);
  img.rect(44, 36, 8, 7, SAND);
  return img;
}

/** 24×24 9-slice dialogue frame with an 8 px inset. */
export function dialogueFrame(): Raster {
  const img = new Raster(24, 24);
  img.rect(0, 0, 24, 24, INK);
  img.rect(2, 2, 20, 20, hex('#8a6a3a'));
  img.rect(3, 3, 18, 18, hex('#efe0b8'));
  for (const [x, y] of [
    [3, 3],
    [20, 3],
    [3, 20],
    [20, 20],
  ] as const)
    img.set(x, y, hex('#f2c230'));
  return img;
}

/** Phaser's built-in textures, bundled so the webview needs no data: images for them (spec §13). */
export function engineTextures(): Record<string, Raster> {
  const missing = new Raster(32, 32);
  for (let y = 0; y < 32; y++) {
    for (let x = 0; x < 32; x++)
      missing.set(x, y, ((x >> 3) + (y >> 3)) % 2 === 0 ? hex('#ff00ff') : hex('#000000'));
  }
  const white = new Raster(4, 4);
  white.rect(0, 0, 4, 4, hex('#ffffff'));
  const blank = new Raster(32, 32);
  blank.rect(0, 0, 32, 32, CLEAR);
  return { 'default.png': blank, 'missing.png': missing, 'white.png': white };
}
