import type { CharacterArt, MapAnimation } from './art.types.ts';
import { type ACTIVITY_KINDS, COUNCIL_ANIMATIONS } from './manifest.ts';
import { CLEAR, hex, Raster } from './raster.ts';

// Placeholder art for the default pack, drawn in code so it can be regenerated byte-for-byte (spec §9.5).
// Real art replaces it at M10.

const F = 16; // character frame and tile size

const HERO = [
  '................',
  '......oooo......',
  '.....ohhhho.....',
  '....ohhhhhho....',
  '....ohhsssso....',
  '....ohsesseo....',
  '....ohhsssso.w..',
  '.....obbbbo..w..',
  '....obbllbbo.w..',
  '...osbbbbbbsow..',
  '....obbbbbbo.w..',
  '....oppppppo....',
  '....opp..ppo....',
  '....opp..ppo....',
  '....off..ffo....',
  '....ooo..ooo....',
];

const COUNCILLOR = [
  '.......oo.......',
  '......ohho......',
  '.....ohhhho.....',
  '....ohhhhhho....',
  '...oooooooooo...',
  '....osssssso....',
  '....osesssso....',
  '....owwwwwwo....',
  '...orrwwwwrro...',
  '..orrrwwwwrrro..',
  '..orrrrwwrrrro..',
  '..orrrrrrrrrro..',
  '..orrryyyyrrro..',
  '..orrrrrrrrrro..',
  '..orrrrrrrrrro..',
  '..oooooooooooo..',
];

const INK = hex('#1a1420');
const SKIN = hex('#f1c19a');
const EYE = hex('#1b1b1b');

export const CHARACTERS: CharacterArt[] = [
  {
    key: 'hero.paladin',
    role: 'hero',
    backdrop: hex('#2d4a7a'),
    palette: {
      o: INK,
      h: hex('#c8ccd4'),
      s: SKIN,
      e: EYE,
      b: hex('#3a6ac0'),
      l: hex('#f2c230'),
      w: hex('#e8e8f0'),
      p: hex('#8a90a0'),
      f: hex('#4a4a58'),
    },
  },
  {
    key: 'hero.barbarian',
    role: 'hero',
    backdrop: hex('#6a2a20'),
    palette: {
      o: INK,
      h: hex('#c0392b'),
      s: hex('#e8b088'),
      e: EYE,
      b: hex('#8a5a3a'),
      l: hex('#3a2a1a'),
      w: hex('#b8c0c8'),
      p: hex('#5a4030'),
      f: hex('#2a1d14'),
    },
  },
  {
    key: 'hero.ranger',
    role: 'hero',
    backdrop: hex('#2a5a2a'),
    palette: {
      o: INK,
      h: hex('#3f8a3a'),
      s: SKIN,
      e: EYE,
      b: hex('#7a9a3a'),
      l: hex('#6b4423'),
      w: hex('#9a6a3b'),
      p: hex('#4a3a2a'),
      f: hex('#2a1d14'),
    },
  },
  {
    key: 'hero.rogue',
    role: 'hero',
    backdrop: hex('#3a2a4a'),
    palette: {
      o: INK,
      h: hex('#4a3a5a'),
      s: hex('#d9a77f'),
      e: EYE,
      b: hex('#5a5a6a'),
      l: hex('#8a2a4a'),
      w: hex('#c8c8d0'),
      p: hex('#2a2a3a'),
      f: hex('#1a1a24'),
    },
  },
  {
    key: 'councillor.elder',
    role: 'councillor',
    backdrop: hex('#4a3a6a'),
    palette: {
      o: INK,
      h: hex('#5a3d8a'),
      s: SKIN,
      e: EYE,
      w: hex('#e8e8e8'),
      r: hex('#6e4aa8'),
      y: hex('#f2c230'),
    },
  },
  {
    key: 'councillor.default',
    role: 'councillor',
    backdrop: hex('#2a5a5a'),
    palette: {
      o: INK,
      h: hex('#2d6a6a'),
      s: hex('#d9a77f'),
      e: EYE,
      w: hex('#c8c8c8'),
      r: hex('#3a8a8a'),
      y: hex('#e86a3a'),
    },
  },
];

/**
 * The map animations each role's placeholder sheet has, one row each in this order (#222): heroes get
 * every optional pose but `review`, which is a councillor's.
 */
export const HERO_ANIMATIONS = [
  'idle',
  'walk',
  'work',
  'test',
  'ask',
  'blocked',
  'rest',
  'celebrate',
  'hurt',
  'outOfGold',
] as const satisfies readonly MapAnimation[];
export const COUNCILLOR_ANIMATIONS = [
  'idle',
  'walk',
  'work',
  'review',
] as const satisfies readonly MapAnimation[];
export const FRAMES = 4;

/** A role's placeholder map animations, in row order. */
export function characterAnimations(role: CharacterArt['role']): readonly MapAnimation[] {
  return role === 'hero' ? HERO_ANIMATIONS : COUNCILLOR_ANIMATIONS;
}

/** One animation frame as template rows: bobbing, stepping or tool motion applied to the base pose. */
function frameRows({
  base,
  role,
  animation,
  i,
}: {
  base: readonly string[];
  role: CharacterArt['role'];
  animation: MapAnimation;
  i: number;
}): string[] {
  let rows = base.map((r) => r);
  const shiftDown = (n: number) => {
    rows = [...Array(n).fill('.'.repeat(F)), ...rows.slice(0, F - n)];
  };
  const shiftUp = (n: number) => {
    rows = [...rows.slice(n), ...Array(n).fill('.'.repeat(F))];
  };
  const shiftLeft = (n: number) => {
    rows = rows.map((r) => r.slice(n) + '.'.repeat(n));
  };
  const swap = (from: string, to: string) => {
    rows = rows.map((r) => r.replaceAll(from, to));
  };
  const put = ({ x, y, key }: { x: number; y: number; key: string }) => {
    const grid = rows.map((r) => [...r]);
    (grid[y] as string[])[x] = key;
    rows = grid.map((g) => g.join(''));
  };
  const liftColumns = ({ from, to, top }: { from: number; to: number; top: number }) => {
    // Move pixels in columns [from, to) of rows top..15 up by one.
    const grid = rows.map((r) => [...r]);
    for (let y = top; y < F; y++) {
      for (let x = from; x < to; x++) {
        (grid[y - 1] as string[])[x] = (grid[y] as string[])[x] as string;
        (grid[y] as string[])[x] = '.';
      }
    }
    rows = grid.map((g) => g.join(''));
  };
  const moveKey = (key: string, dy: number) => {
    if (dy === 0) return;
    const grid = rows.map((r) => [...r]);
    const cells: [number, number][] = [];
    grid.forEach((row, y) => {
      row.forEach((ch, x) => {
        if (ch === key) cells.push([x, y]);
      });
    });
    for (const [x, y] of cells) (grid[y] as string[])[x] = '.';
    for (const [x, y] of cells) if (y + dy >= 0 && y + dy < F) (grid[y + dy] as string[])[x] = key;
    rows = grid.map((g) => g.join(''));
  };

  if (animation === 'idle') {
    if (i >= 2) shiftDown(1);
  } else if (animation === 'test') {
    // A flask raised and shaken, a bubble rising from it.
    moveKey('w', i % 2 === 0 ? -2 : -1);
    put({ x: 13, y: 3 - (i % 2), key: 'l' });
  } else if (animation === 'ask') {
    // A hand up, waving.
    moveKey('w', -3);
    if (i % 2 === 1) shiftDown(1);
  } else if (animation === 'blocked') {
    // Slumped, the weapon lowered, barely moving.
    shiftDown(1);
    moveKey('w', 1);
    if (i === 2) shiftDown(1);
  } else if (animation === 'rest') {
    // Sitting down, breathing slowly.
    shiftDown(3);
    if (i >= 2) shiftDown(1);
  } else if (animation === 'celebrate') {
    // A jump with the weapon up.
    shiftUp([0, 2, 3, 1][i] ?? 0);
    moveKey('w', -2);
  } else if (animation === 'hurt') {
    // Knocked back, flashing its accent colour.
    if (i % 2 === 0) {
      shiftLeft(1);
      swap('b', 'l');
    }
  } else if (animation === 'outOfGold') {
    // Empty-handed, head down.
    swap('w', '.');
    shiftDown(i >= 2 ? 2 : 1);
  } else if (animation === 'review') {
    // Peering closely: a lens sweeps across in front of the face.
    put({ x: 10 + (i % 2 === 0 ? i / 2 : 3 - i), y: 6, key: 'y' });
    put({ x: 10 + (i % 2 === 0 ? i / 2 : 3 - i), y: 7, key: 'o' });
  } else if (animation === 'walk') {
    if (role === 'hero') {
      if (i === 1) liftColumns({ from: 4, to: 8, top: 12 });
      if (i === 3) liftColumns({ from: 8, to: 12, top: 12 });
    } else if (i % 2 === 1) {
      liftColumns({ from: i === 1 ? 2 : 8, to: i === 1 ? 8 : 14, top: 14 });
    }
    if (i % 2 === 1) shiftDown(1);
  } else if (role === 'hero') {
    moveKey('w', [-1, 0, 1, 0][i] ?? 0);
  } else {
    // councillor at work: a spark of insight travels up beside them
    const grid = rows.map((r) => [...r]);
    (grid[9 - i] as string[])[14] = 'y';
    rows = grid.map((g) => g.join(''));
  }
  return rows;
}

export function characterSheet(art: CharacterArt): Raster {
  const base = art.role === 'hero' ? HERO : COUNCILLOR;
  const animations = characterAnimations(art.role);
  const sheet = new Raster(F * FRAMES, F * animations.length);
  animations.forEach((animation, row) => {
    for (let i = 0; i < FRAMES; i++) {
      sheet.pattern({
        x: i * F,
        y: row * F,
        rows: frameRows({ base, role: art.role, animation, i }),
        palette: art.palette,
      });
    }
  });
  return sheet;
}

export function portrait(art: CharacterArt): Raster {
  const p = new Raster(64, 64);
  p.rect({ x: 0, y: 0, w: 64, h: 64, color: INK });
  p.rect({ x: 2, y: 2, w: 60, h: 60, color: art.backdrop });
  const sprite = new Raster(F, F);
  sprite.pattern({
    x: 0,
    y: 0,
    rows: art.role === 'hero' ? HERO : COUNCILLOR,
    palette: art.palette,
  });
  p.blit({ src: sprite, x: 8, y: 10, scale: 3 });
  return p;
}

// ---------- council sheets (48×48 full-body, the council hut only, §9.2) ----------

const C = 48;
/** Where the hut's table hides a council figure: rows from here down (its lower third, #219). */
const TABLE_ROW = 32;

/** A councillor seen at the hut, head to hem: hood, face, beard, robe. 'm' is the mouth. Legs are drawn per frame. */
const COUNCILLOR_48: readonly string[] = (() => {
  const blank = '.'.repeat(C);
  const pad = (row: string) => `${'.'.repeat(8)}${row}${'.'.repeat(8)}`;
  const head = [
    '...............oo...............',
    '..............ohho..............',
    '.............ohhhho.............',
    '............ohhhhhho............',
    '...........ohhhhhhhho...........',
    '..........ohhhhhhhhhho..........',
    '.........ohhhhhhhhhhhho.........',
    '........oooooooooooooooo........',
    '.........osssssssssssso.........',
    '.........osssssssssssso.........',
    '.........osseesssseesso.........',
    '.........osseesssseesso.........',
    '.........osssssssssssso.........',
    '.........ossssssmmsssso.........',
    '.........owwwwwwwwwwwwo.........',
  ].map(pad);
  const robe: string[] = [];
  for (let y = 17; y <= 43; y++) {
    const half = Math.round(10 + (4 * (y - 17)) / 26);
    const beard = y <= 24 ? Math.max(1, 6 - (y - 17)) : 0;
    const row = [...blank];
    for (let x = C / 2 - half; x < C / 2 + half; x++) {
      const edge = x === C / 2 - half || x === C / 2 + half - 1 || y === 43;
      const inBeard = Math.abs(x - (C / 2 - 0.5)) < beard;
      row[x] = edge ? 'o' : inBeard ? 'w' : y === 30 ? 'y' : 'r';
    }
    robe.push(row.join(''));
  }
  return [blank, blank, ...head, ...robe, blank, blank, blank, blank];
})();

/** Two legs under the hem in rows 44–47, the back and front one nudged sideways when walking. */
function drawLegs({ grid, back, front }: { grid: string[][]; back: number; front: number }): void {
  const leg = (x0: number) => {
    for (let y = 44; y <= 46; y++) {
      const row = grid[y] as string[];
      row[x0] = 'o';
      row[x0 + 1] = 'h';
      row[x0 + 2] = 'h';
      row[x0 + 3] = 'o';
    }
    for (let x = x0 - 1; x <= x0 + 4; x++) (grid[47] as string[])[x] = 'o';
  };
  leg(18 + back);
  leg(26 + front);
}

/** One council frame: a full figure; hands work above row TABLE_ROW, where the table starts. */
export function councilFrameRows({
  animation,
  i,
}: {
  animation: (typeof COUNCIL_ANIMATIONS)[number];
  i: number;
}): string[] {
  const grid = COUNCILLOR_48.map((r) => [...r]);
  const paint = ({
    x,
    y,
    w = 1,
    h = 1,
    ch,
  }: {
    x: number;
    y: number;
    w?: number;
    h?: number;
    ch: string;
  }) => {
    for (let yy = y; yy < y + h; yy++)
      for (let xx = x; xx < x + w; xx++) (grid[yy] as string[])[xx] = ch;
  };
  let bob = 0;
  let legs = { back: 0, front: 0 };
  if (animation === 'idle') {
    bob = i >= 2 ? 1 : 0;
  } else if (animation === 'talk') {
    // The mouth opens on every other frame.
    if (i % 2 === 1) paint({ x: 24, y: 15, w: 2, h: 2, ch: 'o' });
  } else if (animation === 'think') {
    // Eyes closed, a hand on the beard, a thought rising beside the head.
    paint({ x: 19, y: 12, w: 2, ch: 's' });
    paint({ x: 26, y: 12, w: 2, ch: 's' });
    paint({ x: 19, y: 13, w: 2, ch: 'o' });
    paint({ x: 26, y: 13, w: 2, ch: 'o' });
    paint({ x: 21, y: 18, w: 5, h: 4, ch: 'o' });
    paint({ x: 22, y: 19, w: 3, h: 2, ch: 's' });
    for (let d = 0; d <= i; d++) paint({ x: 34 + d * 2, y: 10 - d * 3, w: 2, h: 2, ch: 'y' });
  } else if (animation === 'raiseHand') {
    // An arm raised on the right; the hand waves left and right.
    const dx = [0, 1, 0, -1][i] ?? 0;
    paint({ x: 34, y: 8, w: 3, h: 14, ch: 'o' });
    paint({ x: 35, y: 9, w: 1, h: 13, ch: 'r' });
    paint({ x: 33 + dx, y: 3, w: 5, h: 5, ch: 'o' });
    paint({ x: 34 + dx, y: 4, w: 3, h: 3, ch: 's' });
  } else if (animation === 'write') {
    // Writing: a hand with a quill moving along just above the table.
    const dx = i * 3;
    paint({ x: 13 + dx, y: TABLE_ROW - 6, w: 5, h: 4, ch: 'o' });
    paint({ x: 14 + dx, y: TABLE_ROW - 5, w: 3, h: 2, ch: 's' });
    paint({ x: 17 + dx, y: TABLE_ROW - 10, w: 1, h: 5, ch: 'w' });
    paint({ x: 18 + dx, y: TABLE_ROW - 11, w: 1, h: 2, ch: 'w' });
  } else {
    // Walking in, facing right: legs apart, together (body a pixel up), apart the other way, together.
    legs = [
      { back: -2, front: 2 },
      { back: 0, front: 0 },
      { back: 2, front: -2 },
      { back: 0, front: 0 },
    ][i] ?? { back: 0, front: 0 };
    bob = i % 2 === 1 ? -1 : 0;
  }
  drawLegs({ grid, ...legs });
  const rows = grid.map((g) => g.join(''));
  // Bobbing moves the body above the legs: a pixel down, or a pixel up.
  if (bob === 1) return ['.'.repeat(C), ...rows.slice(0, 43), ...rows.slice(44)];
  if (bob === -1) return [...rows.slice(1, 44), '.'.repeat(C), ...rows.slice(44)];
  return rows;
}

/** A councillor's 48×48 council sheet: one row per council animation, FRAMES frames each. */
export function councilSheet(art: CharacterArt): Raster {
  const sheet = new Raster(C * FRAMES, C * COUNCIL_ANIMATIONS.length);
  COUNCIL_ANIMATIONS.forEach((animation, row) => {
    for (let i = 0; i < FRAMES; i++) {
      sheet.pattern({
        x: i * C,
        y: row * C,
        rows: councilFrameRows({ animation, i }),
        palette: { ...art.palette, m: hex('#b07a5a') },
      });
    }
  });
  return sheet;
}

// ---------- map ----------

const WATER = hex('#2b5f9e');
const WATER_LIGHT = hex('#336db0');
const WAVE = hex('#8fc1ef');
const GRASS = hex('#5dab3c');
const GRASS_DARK = hex('#4a9530');
const SAND = hex('#e8d48a');
const SAND_DARK = hex('#cdb56a');
const CLIFF = hex('#8a5a2e');
const CLIFF_DARK = hex('#5e3b1c');
const FOAM = hex('#d8ecff');
const DOT = hex('#f3ead2');
const DOT_SHADOW = hex('#1f4a7c');

/** Tile strip: water ×4 (animated), grass, sand, shore, path dot. */
export const TILE_INDEX = { water: 0, grass: 4, sand: 5, shore: 6, pathDot: 7 } as const;

export function tiles(): Raster {
  const t = new Raster(F * 8, F);
  for (let f = 0; f < 4; f++) {
    const x0 = f * F;
    t.rect({ x: x0, y: 0, w: F, h: F, color: WATER });
    t.rect({ x: x0, y: 8, w: F, h: 8, color: WATER_LIGHT });
    t.rect({ x: x0 + ((2 + f * 3) % F), y: 4, w: 3, h: 1, color: WAVE });
    t.rect({ x: x0 + ((9 + f * 3) % 13), y: 11, w: 3, h: 1, color: WAVE });
  }
  t.rect({ x: 4 * F, y: 0, w: F, h: F, color: GRASS });
  for (const [x, y] of [
    [3, 4],
    [10, 2],
    [7, 11],
    [13, 9],
  ] as const)
    t.rect({ x: 4 * F + x, y, w: 1, h: 2, color: GRASS_DARK });
  t.rect({ x: 5 * F, y: 0, w: F, h: F, color: SAND });
  for (const [x, y] of [
    [2, 3],
    [11, 6],
    [6, 12],
  ] as const)
    t.set({ x: 5 * F + x, y, color: SAND_DARK });
  t.rect({ x: 6 * F, y: 0, w: F, h: 10, color: GRASS });
  t.rect({ x: 6 * F, y: 10, w: F, h: 6, color: SAND });
  t.rect({ x: 6 * F, y: 10, w: F, h: 1, color: SAND_DARK });
  t.rect({ x: 7 * F + 7, y: 7, w: 2, h: 2, color: DOT_SHADOW });
  t.rect({ x: 7 * F + 7, y: 6, w: 2, h: 2, color: DOT });
  return t;
}

/** One island at minimum width: left cap 48, one repeatable middle 32, right cap 48; 96 tall (§9.2). */
export function island(): Raster {
  const w = 128;
  const img = new Raster(w, 96);
  const insetTop = [8, 5, 3, 2, 1, 1];
  for (let r = 0; r < 96; r++) {
    const inset = r >= 84 ? 2 + (r - 84) : r < 6 ? (insetTop[r] as number) : 0;
    const color = r < 2 ? SAND : r < 58 ? GRASS : r < 64 ? SAND : r < 86 ? CLIFF : FOAM;
    img.rect({ x: inset, y: r, w: w - inset * 2, h: 1, color });
    if (color === GRASS) {
      img.rect({ x: inset, y: r, w: 2, h: 1, color: SAND });
      img.rect({ x: w - inset - 2, y: r, w: 2, h: 1, color: SAND });
    }
    if (color === CLIFF) {
      for (let x = inset + 3; x < w - inset; x += 8)
        img.set({ x: x + (r % 3 === 0 ? 1 : 0), y: r, color: CLIFF_DARK });
    }
    if (r === 63) img.rect({ x: inset, y: r, w: w - inset * 2, h: 1, color: SAND_DARK });
  }
  // Tufts repeat every 32 px so the middle slice tiles seamlessly.
  for (let x = 6; x < w - 6; x += 32) {
    for (const [dx, dy] of [
      [4, 10],
      [15, 30],
      [24, 18],
      [9, 44],
    ] as const) {
      if (x + dx + 2 > w - 4) continue; // keep the sand rim clear
      img.rect({ x: x + dx, y: dy, w: 1, h: 2, color: GRASS_DARK });
      img.set({ x: x + dx + 1, y: dy + 1, color: GRASS_DARK });
    }
  }
  return img;
}

export const TASK_POINT_COLORS = {
  locked: hex('#8a8a8a'),
  active: hex('#f2c230'),
  done: hex('#4fd16a'),
  underReview: hex('#6aa8ff'),
} as const;

/** Task point states left to right, each with its own icon so colour is never the only signal (§7.4). */
export function taskPoints(states: readonly (keyof typeof TASK_POINT_COLORS)[]): Raster {
  const img = new Raster(F * states.length, F);
  states.forEach((state, i) => {
    const x = i * F;
    const color = TASK_POINT_COLORS[state];
    img.rect({ x: x + 2, y: 3, w: 12, h: 11, color: INK });
    img.rect({ x: x + 3, y: 2, w: 10, h: 13, color: INK });
    img.rect({ x: x + 3, y: 3, w: 10, h: 10, color });
    img.rect({ x: x + 4, y: 2, w: 8, h: 12, color });
    if (state === 'locked') {
      img.rect({ x: x + 6, y: 5, w: 4, h: 1, color: INK });
      img.rect({ x: x + 5, y: 6, w: 1, h: 2, color: INK });
      img.rect({ x: x + 10, y: 6, w: 1, h: 2, color: INK });
      img.rect({ x: x + 5, y: 8, w: 6, h: 4, color: INK });
    } else if (state === 'active') {
      img.rect({ x: x + 7, y: 5, w: 2, h: 4, color: INK });
      img.rect({ x: x + 7, y: 10, w: 2, h: 2, color: INK });
    } else if (state === 'done') {
      for (const [dx, dy] of [
        [5, 8],
        [6, 9],
        [7, 10],
        [8, 9],
        [9, 8],
        [10, 7],
        [11, 6],
      ] as const)
        img.set({ x: x + dx, y: dy, color: INK });
    } else {
      img.rect({ x: x + 5, y: 7, w: 6, h: 3, color: INK });
      img.rect({ x: x + 7, y: 8, w: 2, h: 1, color });
    }
  });
  return img;
}

const PLANK = hex('#b07a3e');
const PLANK_DARK = hex('#7a4e22');
const CHAIN = hex('#9aa0a8');

/**
 * A stacked plan's drawbridge (§9.2, #124): rows `lowered` then `raised`, each a left end (8), a segment
 * (32) that repeats, and a right end (8), 24 tall. Lowered: planks across with posts at both ends.
 * Raised: the deck tilted up on its left post, open water under it, chains taut.
 */
export function bridge(): Raster {
  const end = 8;
  const segment = 32;
  const h = 24;
  const img = new Raster(end * 2 + segment, h * 2);
  const post = (x: number, y: number) => {
    img.rect({ x, y: y + 2, w: 4, h: 20, color: CLIFF_DARK });
    img.rect({ x: x + 1, y: y + 1, w: 2, h: 1, color: CLIFF });
  };
  // Lowered.
  post(2, 0);
  post(end * 2 + segment - 6, 0);
  for (let x = end; x < end + segment; x++) {
    img.rect({ x, y: 9, w: 1, h: 7, color: x % 4 === 0 ? PLANK_DARK : PLANK });
  }
  img.rect({ x: 0, y: 9, w: end, h: 7, color: PLANK });
  img.rect({ x: end + segment, y: 9, w: end, h: 7, color: PLANK });
  img.rect({ x: 0, y: 16, w: end * 2 + segment, h: 1, color: PLANK_DARK });
  // Raised: the deck stands up beside the left post; the segment is open water.
  post(2, h);
  post(end * 2 + segment - 6, h);
  img.rect({ x: end - 2, y: h + 1, w: 6, h: 20, color: PLANK });
  img.rect({ x: end + 3, y: h + 1, w: 1, h: 20, color: PLANK_DARK });
  for (let x = end + 4; x < end + segment; x += 3) img.set({ x, y: h + 3, color: CHAIN });
  img.rect({ x: end + segment, y: h + 9, w: end, h: 7, color: PLANK });
  return img;
}

/**
 * Map markers: a padlock over a blocked hero, a "behind" mark (two arrows back) (#124), a reviewer's
 * magnifier and an hourglass over a hero waiting under review (#140).
 */
export function markers(): Raster {
  const s = 12;
  const img = new Raster(s * 4, s);
  img.pattern({
    x: 0,
    y: 0,
    rows: [
      '............',
      '....kkkk....',
      '...k....k...',
      '...k....k...',
      '...k....k...',
      '..kkkkkkkk..',
      '..kyyyyyyk..',
      '..kyyykyyk..',
      '..kyyykyyk..',
      '..kyyyyyyk..',
      '..kkkkkkkk..',
      '............',
    ],
    palette: { k: INK, y: hex('#f2c230') },
  });
  img.pattern({
    x: s,
    y: 0,
    rows: [
      '............',
      '..kkkkkkkk..',
      '.kooooooook.',
      '.koookoookk.',
      '.kookkookok.',
      '.kokkkokkok.',
      '.kookkookok.',
      '.koookoookk.',
      '.kooooooook.',
      '..kkkkkkkk..',
      '............',
      '............',
    ],
    palette: { k: INK, o: hex('#f28a30') },
  });
  // A reviewer's magnifier (#140): a glass with a handle.
  img.pattern({
    x: s * 2,
    y: 0,
    rows: [
      '............',
      '...kkkk.....',
      '..kbbbbk....',
      '.kbwbbbbk...',
      '.kbbbbbbk...',
      '.kbbbbbbk...',
      '..kbbbbk....',
      '...kkkkhh...',
      '.......hhh..',
      '........hhh.',
      '.........hh.',
      '............',
    ],
    palette: { k: INK, b: hex('#9fd4f2'), w: hex('#ffffff'), h: hex('#8a5a2a') },
  });
  // A hero waiting under review (#140): an hourglass.
  img.pattern({
    x: s * 3,
    y: 0,
    rows: [
      '............',
      '..kkkkkkkk..',
      '...kyyyyk...',
      '...kyyyyk...',
      '....kyyk....',
      '.....kk.....',
      '....k..k....',
      '...k.yy.k...',
      '...kyyyyk...',
      '..kkkkkkkk..',
      '............',
      '............',
    ],
    palette: { k: INK, y: hex('#e8c87a') },
  });
  return img;
}

export function hut(): Raster {
  const img = new Raster(64, 64);
  img.rect({ x: 8, y: 28, w: 48, h: 34, color: hex('#7a4a24') });
  for (let i = 0; i < 34; i += 4) img.rect({ x: 8, y: 28 + i, w: 48, h: 1, color: hex('#5e3818') });
  for (let r = 0; r < 28; r++) {
    const half = 4 + r;
    img.rect({
      x: 32 - half,
      y: r + 2,
      w: half * 2,
      h: 1,
      color: r % 4 === 0 && r > 0 ? hex('#8a2a20') : hex('#b8392b'),
    });
  }
  img.rect({ x: 26, y: 44, w: 12, h: 18, color: hex('#2a1a10') });
  img.rect({ x: 35, y: 53, w: 1, h: 2, color: hex('#f2c230') });
  img.rect({ x: 12, y: 36, w: 8, h: 7, color: SAND });
  img.rect({ x: 44, y: 36, w: 8, h: 7, color: SAND });
  return img;
}

/**
 * The Guild Hall (§7.1, #179): Ibitsa's settings, in Home Village beside the hut. A stone hall with a
 * slate roof, a banner and a door, 48×48.
 */
export function guildHall(): Raster {
  const img = new Raster(48, 48);
  const stone = hex('#9a9a9a');
  const stoneDark = hex('#6e6e6e');
  img.rect({ x: 4, y: 20, w: 40, h: 26, color: stone });
  for (let y = 22; y < 46; y += 4) img.rect({ x: 4, y, w: 40, h: 1, color: stoneDark });
  for (let r = 0; r < 18; r++) {
    const half = 6 + r;
    img.rect({
      x: 24 - half,
      y: r + 2,
      w: half * 2,
      h: 1,
      color: r % 3 === 0 ? hex('#3a4a6a') : hex('#4a5d82'),
    });
  }
  img.rect({ x: 19, y: 32, w: 10, h: 14, color: hex('#2a1a10') });
  img.rect({ x: 26, y: 39, w: 1, h: 2, color: hex('#f2c230') });
  // The banner: Ibitsa's gold on blue, hanging from the roof's edge.
  img.rect({ x: 8, y: 22, w: 6, h: 10, color: hex('#2f5fb0') });
  img.rect({ x: 10, y: 25, w: 2, h: 3, color: hex('#f2c230') });
  img.rect({ x: 34, y: 24, w: 6, h: 5, color: SAND });
  return img;
}

/** 24×24 9-slice dialogue frame with an 8 px inset. */
export function dialogueFrame(): Raster {
  const img = new Raster(24, 24);
  img.rect({ x: 0, y: 0, w: 24, h: 24, color: INK });
  img.rect({ x: 2, y: 2, w: 20, h: 20, color: hex('#8a6a3a') });
  img.rect({ x: 3, y: 3, w: 18, h: 18, color: hex('#efe0b8') });
  for (const [x, y] of [
    [3, 3],
    [20, 3],
    [3, 20],
    [20, 20],
  ] as const)
    img.set({ x, y, color: hex('#f2c230') });
  return img;
}

/** Phaser's built-in textures, bundled so the webview needs no data: images for them (spec §13). */
export function engineTextures(): Record<string, Raster> {
  const missing = new Raster(32, 32);
  for (let y = 0; y < 32; y++) {
    for (let x = 0; x < 32; x++)
      missing.set({
        x,
        y,
        color: ((x >> 3) + (y >> 3)) % 2 === 0 ? hex('#ff00ff') : hex('#000000'),
      });
  }
  const white = new Raster(4, 4);
  white.rect({ x: 0, y: 0, w: 4, h: 4, color: hex('#ffffff') });
  const blank = new Raster(32, 32);
  blank.rect({ x: 0, y: 0, w: 32, h: 32, color: CLEAR });
  return { 'default.png': blank, 'missing.png': missing, 'white.png': white };
}

// ---------- activity icons (#60) ----------

/** A cream badge with an ink rim; each glyph draws on top. 12×12, readable beside a 16 px hero. */
const BADGE = [
  '..oooooooo..',
  '.occcccccco.',
  'occcccccccco',
  'occcccccccco',
  'occcccccccco',
  'occcccccccco',
  'occcccccccco',
  'occcccccccco',
  'occcccccccco',
  'occcccccccco',
  '.occcccccco.',
  '..oooooooo..',
];

const GLYPHS: Record<(typeof ACTIVITY_KINDS)[number], readonly string[]> = {
  read: [
    '............',
    '............',
    '............',
    '..bbbb.bbbb.',
    '..bwwb.bwwb.',
    '..bwwb.bwwb.',
    '..bwwb.bwwb.',
    '..bbbbbbbbb.',
    '......b.....',
    '............',
    '............',
    '............',
  ],
  search: [
    '............',
    '............',
    '...gggg.....',
    '..g....g....',
    '..g.ww.g....',
    '..g.w..g....',
    '..g....g....',
    '...gggg.....',
    '.......kk...',
    '........kk..',
    '............',
    '............',
  ],
  edit: [
    '............',
    '............',
    '...ssss.....',
    '..ssssss....',
    '...ssss.....',
    '.....k......',
    '......k.....',
    '.......k....',
    '........k...',
    '.........k..',
    '............',
    '............',
  ],
  test: [
    '............',
    '............',
    '....kkk.....',
    '.....k......',
    '.....k......',
    '....kgk.....',
    '...kgggk....',
    '..kgggggk...',
    '..kgggggk...',
    '...kkkkk....',
    '............',
    '............',
  ],
  run: [
    '............',
    '............',
    '..kkkkkkkk..',
    '..kddddddk..',
    '..kdwddddk..',
    '..kddwdddk..',
    '..kdwdwwdk..',
    '..kddddddk..',
    '..kkkkkkkk..',
    '............',
    '............',
    '............',
  ],
  think: [
    '............',
    '...kkkkkk...',
    '..kuuuuuuk..',
    '.kuuuuuuuuk.',
    '.kuuuuuuuuk.',
    '..kuuuuuuk..',
    '...kkkkkk...',
    '....kk......',
    '...kk.......',
    '..k.........',
    '............',
    '............',
  ],
  other: [
    '............',
    '............',
    '.....kk.....',
    '...k.kk.k...',
    '....kkkk....',
    '..kkk..kkk..',
    '..kkk..kkk..',
    '....kkkk....',
    '...k.kk.k...',
    '.....kk.....',
    '............',
    '............',
  ],
};

const ICON_PALETTE = {
  o: INK,
  c: hex('#fff6dc'),
  k: INK,
  b: hex('#7a4a24'),
  w: hex('#fdfaf0'),
  g: hex('#3f9b4a'),
  s: hex('#8a8f98'),
  d: hex('#2a2f3a'),
  u: hex('#cfe3f5'),
};

/** The activity icon strip: one 12×12 badge per kind, in the order given. */
export function activityIcons(kinds: readonly (keyof typeof GLYPHS)[]): Raster {
  const size = 12;
  const img = new Raster(size * kinds.length, size);
  kinds.forEach((kind, i) => {
    img.pattern({ x: i * size, y: 0, rows: BADGE, palette: ICON_PALETTE });
    img.pattern({ x: i * size, y: 0, rows: GLYPHS[kind], palette: ICON_PALETTE });
  });
  return img;
}
